### ISSUE TITLE
currentColor doesn't work in combination with inheriting colors (Safari)

### ISSUE THREAD

**Issue by TimonVS** [basscss/button-outline#3]
The `currentColor` keyword doesn't seem to work correctly in Safari when you use `color: inherit;` on the parent element and `background-color: currentColor;` on child elements.

Demo: http://jsfiddle.net/e43tmk9c/4/

I already filed a bug report. But I just wanted to let you know that it may not be safe to use the `currentColor` keyword already.

**Comment by jxnblk** [comment]
Thanks. I'm aware of the `currentcolor` issues in Safari, and I'll be deprecating the `button-outline` and `button-transparent` modules in favor of something simpler in Basscss v7.

Since this is a browser bug, I'm not sure there's anything I can do to fix this issue here.
